apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aeyvwq7s3-go
  janus-idp.io/tekton: aeyvwq7s3-go
  backstage.io/kubernetes-id: aeyvwq7s3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aeyvwq7s3-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
